### ISSUE TITLE
Crash on Windows 7

### ISSUE THREAD

**Issue by Xinnony** [sourcechord/FluentWPF#157]
Hi,
I have a crash on windows 7 with FluentWPF.

See the log :

```
System.DllNotFoundException: Impossible de charger la DLL 'shcore.dll': Le module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)
at SourceChord.FluentWPF.AcrylicWindow.GetDpiForMonitor(IntPtr hMonitor, MONITOR_DPI_TYPE dpiType, UInt32& dpiX, UInt32& dpiY)
at SourceChord.FluentWPF.AcrylicWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I thinks is same problem of this program : https://github.com/dnGrep/dnGrep/issues/372
Probably fixed in : https://github.com/dnGrep/dnGrep/commit/0a733873af9679f27583e0671212cecd8dccf705

In my code i just have :
```
<Window ...
        xmlns:fw="clr-namespace:SourceChord.FluentWPF;assembly=FluentWPF"
        fw:AcrylicWindow.Enabled="True"
        fw:AcrylicWindow.FallbackColor="#222222"
        fw:AcrylicWindow.NoiseOpacity="0"
        fw:AcrylicWindow.ExtendViewIntoTitleBar="True"
        ui:WindowHelper.UseModernWindowStyle="True"
        ui:TitleBar.IsIconVisible="True"
        ...>
...
</Window>
```

**Comment by Xinnony** [comment]
Pull request created.
