### ISSUE TITLE
Issue with reveal effect

### ISSUE THREAD

**Issue by Symbai** [sourcechord/FluentWPF#24]
Installed the nuget package and followed the examples. Got an AcrylicWindow with a grid where PointerTracker.Enabled is set to true. Then stackpanel then the buttons in the example with the styles ButtonRevealStyle.

When I launch the app the output automatically gives lots of binding errors:

```
System.Windows.Data Error: 17 : Cannot get 'IsEnter' value (type 'Boolean') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=53954942); target property is 'Opacity' (type 'Double') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'RootObject' value (type 'UIElement') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=53954942); target property is 'Center' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'Position' value (type 'Point') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=53954942); target property is 'Center' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'RootObject' value (type 'UIElement') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=53954942); target property is 'GradientOrigin' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'Position' value (type 'Point') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=53954942); target property is 'GradientOrigin' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Error: 17 : Cannot get 'IsEnter' value (type 'Boolean') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=15832433); target property is 'Opacity' (type 'Double') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'RootObject' value (type 'UIElement') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=15832433); target property is 'Center' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'Position' value (type 'Point') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=15832433); target property is 'Center' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'RootObject' value (type 'UIElement') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=15832433); target property is 'GradientOrigin' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'Position' value (type 'Point') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=15832433); target property is 'GradientOrigin' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Error: 17 : Cannot get 'IsEnter' value (type 'Boolean') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=11244347); target property is 'Opacity' (type 'Double') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'RootObject' value (type 'UIElement') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=11244347); target property is 'Center' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'Position' value (type 'Point') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=11244347); target property is 'Center' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'RootObject' value (type 'UIElement') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=11244347); target property is 'GradientOrigin' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Warning: 17 : Cannot get 'Position' value (type 'Point') from '' (type 'SharedDp'). BindingExpression:Path=(0); DataItem='SharedDp' (HashCode=20908074); target element is 'RadialGradientBrush' (HashCode=11244347); target property is 'GradientOrigin' (type 'Point') InvalidCastException:'System.InvalidCastException: The object of the type "System.Windows.SharedDp" can not be in type "System.Windows.DependencyObject" being transformed.
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Window', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'SolidColorBrush' (HashCode=20798117); target property is 'Color' (type 'Color')

```

**Comment by sourcechord** [comment]
Hi, @Symbai.

Thanks for your feedbak.
I recognized this issue.
And, trying to fix it.

**Comment by sourcechord** [comment]
This has not been fixed yet.
I'll fix it in the next release.
