### ISSUE TITLE
Class library exception issue

### ISSUE THREAD

**Issue by nima70** [sourcechord/FluentWPF#74]
Hi 
I used the package in a normal WPF application. And It worked fine.
Now I 'm trying to set up the package inside a class library. But I m getting the following exception.
==========================================================
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=The invocation of the constructor on type 'SourceChord.FluentWPF.ResourceDictionaryEx' that matches the specified binding constraints threw an exception.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at V4.WPF.GUI.MainWindow.InitializeComponent() in D:\Vitrox\V4_x64\V4.WPF.GUI\MainWindow.xaml:line 1

Inner Exception 1:
TypeInitializationException: The type initializer for 'SourceChord.FluentWPF.SystemTheme' threw an exception.

Inner Exception 2:
NullReferenceException: Object reference not set to an instance of an object.

"   at SourceChord.FluentWPF.ThemeHandler..ctor()\r\n   at SourceChord.FluentWPF.SystemTheme..ctor()\r\n   at SourceChord.FluentWPF.SystemTheme..cctor()"
==========================================================

The exception is being occurred at SystemTheme. The inner exception is 

"Object reference not set to an instance of an object." 

![FluentDesign exception](https://user-images.githubusercontent.com/5094767/66289418-37b68300-e90f-11e9-838d-56c72843bc5b.PNG)

Does anyone have any idea on how to resolve this problem?

Thanks and have a great day.

**Comment by sourcechord** [comment]
Hi, @nima70

Sorry for responding so late.
I couldn't reproduce it.
Please tell me more information.

By the way, FluentWPF needs some ResourceDictionaries.
(See also [preparation](https://github.com/sourcechord/FluentWPF#preparation))

If you use FluentWPF in class library, you have to load the ResourceDictionary manualy.

For example, like this in class library.
```cs
var dict = new ResourceDictionary();
dict.Source = new Uri("pack://application:,,,/FluentWPF;component/Styles/Controls.xaml");
Application.Current.Resources.MergedDictionaries.Add(dict);

```
Please try it.

**Comment by nima70** [comment]
Hi
I added the mentioned code inside my Window code behind .
![code behind](https://user-images.githubusercontent.com/5094767/69511099-14f13400-0f7a-11ea-9e66-af92ab989ed3.PNG)
Here is the exception I get
![exception](https://user-images.githubusercontent.com/5094767/69511210-4e29a400-0f7a-11ea-9f86-ae55a3c050ad.PNG)

**Comment by milanLavic** [comment]
Hey @nima70 , did you figure it out? I'm trying to use it in a class library, and I have the same problem.
